"""
Basic usage examples for the Network Subnet Calculator.

This module demonstrates common subnet calculation tasks that network
engineers and IT professionals perform daily.
"""

from calculator.subnet_calculator import SubnetCalculator


def example_1_basic_subnet_info():
    """
        Example 1: Calculate basic subnet information.

                Determine the network address, broadcast address, and usable host
                    range for a given IP address and prefix length.
                        """
                            print("=" * 70)
                                print("Example 1: Basic Subnet Information")
                                    print("=" * 70)

                                            calculator = SubnetCalculator("192.168.1.0", 24)

                                                    print(f"IP Address:        {calculator.ip_address}")
                                                        print(f"CIDR Notation:     {calculator.ip_address}/{calculator.prefix_length}")
                                                            print(f"Subnet Mask:       {calculator.subnet_mask}")
                                                                print(f"Network Address:   {calculator.network_address}")
                                                                    print(f"Broadcast Address: {calculator.broadcast_address}")
                                                                        print(f"Usable Hosts:      {calculator.usable_hosts}")
                                                                            print(f"Host Range:        {calculator.first_usable_host} - {calculator.last_usable_host}")
                                                                                print()


                                                                                def example_2_multiple_subnet_sizes():
                                                                                    """
                                                                                        Example 2: Compare different subnet sizes.

                                                                                                Show how different prefix lengths impact network capacity and
                                                                                                    host availability.
                                                                                                        """
                                                                                                            print("=" * 70)
                                                                                                                print("Example 2: Subnet Size Comparison")
                                                                                                                    print("=" * 70)
                                                                                                                        
                                                                                                                            prefixes = [24, 25, 26, 27, 28]
                                                                                                                                base_ip = "192.168.1.0"
                                                                                                                                    
                                                                                                                                        print(f"{'Prefix':<10} {'Subnet Mask':<20} {'Usable Hosts':<15}")
                                                                                                                                            print("-" * 45)
                                                                                                                                                
                                                                                                                                                    for prefix in prefixes:
                                                                                                                                                            calculator = SubnetCalculator(base_ip, prefix)
                                                                                                                                                                    print(f"/{prefix:<9} {calculator.subnet_mask:<20} {calculator.usable_hosts:<15}")
                                                                                                                                                                        print()
                                                                                                                                                                        
                                                                                                                                                                        
                                                                                                                                                                        def example_3_validate_and_calculate():
                                                                                                                                                                            """
                                                                                                                                                                                Example 3: Validate and calculate with user-provided input.
                                                                                                                                                                                    
                                                                                                                                                                                        Demonstrates error handling when working with invalid input.
                                                                                                                                                                                            """
                                                                                                                                                                                                print("=" * 70)
                                                                                                                                                                                                    print("Example 3: Input Validation")
                                                                                                                                                                                                        print("=" * 70)
                                                                                                                                                                                                            
                                                                                                                                                                                                                test_cases = [
                                                                                                                                                                                                                        ("10.0.0.0", 8),
                                                                                                                                                                                                                                ("172.16.0.0", 12),
                                                                                                                                                                                                                                        ("192.168.0.0", 16),
                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    for ip, prefix in test_cases:
                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                        calculator = SubnetCalculator(ip, prefix)
                                                                                                                                                                                                                                                                                    print(f"✓ {ip}/{prefix:<3} -> {calculator.usable_hosts:>6} usable hosts")
                                                                                                                                                                                                                                                                                            except ValueError as e:
                                                                                                                                                                                                                                                                                                        print(f"✗ {ip}/{prefix:<3} -> Error: {e}")
                                                                                                                                                                                                                                                                                                            print()
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            def example_4_class_c_subnetting():
                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                    Example 4: Practical Class C subnetting for a small office.
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            Divide a single Class C network (192.168.1.0/24) into smaller
                                                                                                                                                                                                                                                                                                                                subnets for different departments.
                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                        print("=" * 70)
                                                                                                                                                                                                                                                                                                                                            print("Example 4: Class C Subnetting for Multiple Departments")
                                                                                                                                                                                                                                                                                                                                                print("=" * 70)
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        departments = {
                                                                                                                                                                                                                                                                                                                                                                "Management":  "192.168.1.0",
                                                                                                                                                                                                                                                                                                                                                                        "Engineering":  "192.168.1.64",
                                                                                                                                                                                                                                                                                                                                                                                "Sales":        "192.168.1.128",
                                                                                                                                                                                                                                                                                                                                                                                        "Support":      "192.168.1.192",
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    print(f"{'Department':<15} {'Network':<20} {'Hosts':<10} {'Broadcast':<15}")
                                                                                                                                                                                                                                                                                                                                                                                                        print("-" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                for dept, ip in departments.items():
                                                                                                                                                                                                                                                                                                                                                                                                                        calculator = SubnetCalculator(ip, 26)
                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"{dept:<15} {ip}/26{'':<12} {calculator.usable_hosts:<10} {calculator.broadcast_address:<15}")
                                                                                                                                                                                                                                                                                                                                                                                                                                    print()
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                        example_1_basic_subnet_info()
                                                                                                                                                                                                                                                                                                                                                                                                                                            example_2_multiple_subnet_sizes()
                                                                                                                                                                                                                                                                                                                                                                                                                                                example_3_validate_and_calculate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                    example_4_class_c_subnetting()
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("=" * 70)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("For more advanced examples, see batch_calculations.py")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("=" * 70)92.168.1.192",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"{'Department':<15} {'Network':<20} {'Hosts':<10} {'Broadcast':<15}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("-" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for dept, ip in departments.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    calculator = SubnetCalculator(ip, 26)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"{dept:<15} {ip}/26{'':<12} {calculator.usable_hosts:<10} {calculator.broadcast_address:<15}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    example_1_basic_subnet_info()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        example_2_multiple_subnet_sizes()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            example_3_validate_and_calculate()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                example_4_class_c_subnetting()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("=" * 70)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("For more advanced examples, see batch_calculations.py")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("=" * 70)
